### PR TITLE
Upgrade sushi to 3.3.1

### PR DESCRIPTION
**Pull request by mikajylha**

### CODE REVIEW

**Comment by mikajylha** [comment]
Having problems locally. Antlr fix needs webpack. Need to tune our docker image or wait longer until we get version without fixAntlr4.

**Review by mrinnetmaki — APPROVED** [review]
Interesting.

Anyway, approving this so it is ready to go when the world is ready for it. :)

**Comment by mikajylha** [comment]
#168 supersedes this.

**Comment by mrinnetmaki** [comment]
Superseded by #168, right?

**Comment by mikajylha** [comment]
yep

**Pull request closed without merging**
